### ISSUE TITLE
Release 0.3 does found src module

### ISSUE THREAD

**Issue by wesley-petit** [VCityTeam/pySunlight#6]
The code in release [0.3](https://github.com/VCityTeam/pySunlight/tree/0.3) return an error on computation : 
```
Traceback (most recent call last):
  File "C:\Users\vcity\Desktop\pySunlight\src\main.py", line 7, in <module>
    from src import pySunlight
  File "c:\users\vcity\desktop\pysunlight\src\__init__.py", line 2, in <module>        
    from .Writers import CsvWriter
  File "c:\users\vcity\desktop\pysunlight\src\Writers\__init__.py", line 2, in <module>
    from .CsvWriter import CsvWriter
ModuleNotFoundError: No module named 'src.Writers.CsvWriter'
```

**Comment by wesley-petit** [comment]
That's because the CsvWriter module was called CSVWriter.
